# Generated by Django 5.1.6 on 2025-03-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_remove_user_email_remove_user_name_remove_user_pwd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('uname', models.TextField()),
                ('pwd', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
