# Generated by Django 5.1.6 on 2025-03-19 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0005_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
